name: Push main code to QA branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: sync qa
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: qa
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
